apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-go
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-go
  template:
    metadata:
      labels:
        app: service-go
    spec:
      containers:
        - name: service-go
          image: nginx
