---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: kafka
      version: "28.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 1  # Для теста, в продуктиве 3
    persistence:
      size: 8Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
