---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: rabbitmq
      version: "15.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: guest
      password: guest
    persistence:
      size: 4Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
