---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prom-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "55.x.x"  # Актуальная версия
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Grafana настройки
    grafana:
      enabled: true
      adminPassword: "admin"  # Временный пароль, в проде через Vault
      service:
        type: NodePort  # Или LoadBalancer если есть
        nodePort: 30001
      ingress:
        enabled: false  # Включить если есть ingress controller
    
    # Prometheus настройки
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "standard"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
    
    # Отключаем ненужные компоненты для экономии ресурсов
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
