---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: mongodb
      version: "15.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      usernames: ["service_user"]
      databases: ["shipments_db"]
      rootPassword: "mongodb_password"  # В продуктиве через Vault
    persistence:
      size: 5Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
