---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: redis
      version: "19.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      enabled: false  # Для теста, в продуктиве включить
    master:
      persistence:
        size: 2Gi
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
