---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: service-py
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: helm/service-py  # ИСПРАВЛЕНО: убрал ./
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
