---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: service-go
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: helm/service-go
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: nginx
      tag: latest
    replicaCount: 1
