apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-go
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: helm/service-go 
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: nginx
      tag: latest
    replicaCount: 1
