apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-simple
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/service-py
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: nginx
      tag: alpine
    replicaCount: 1
