apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/my-cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system


